[package]
name = "pubsubinator"
version = "0.1.2"
edition = "2021"

[dependencies]
embassy-executor   = { version = "0.3.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-futures    = "0.1.0"
embassy-sync       = { version = "0.3.0" }
embassy-time = { version = "0.3.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb        = { git = "https://github.com/embassy-rs/embassy", tag = "embassy-sync-v0.3.0", optional = true, features = ["defmt", "msos-descriptor"] }

embassy-rp    = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0"}
embassy-nrf   = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time"]}
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", optional = true, tag = "embassy-sync-v0.3.0"}

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3.1", features = ["defmt", "defmt-error", "print-defmt"] }
fixed = "1.24.0"
static_cell = "1.2"

cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
rand = { version = "0.8.5", default-features = false }
futures = { version = "0.3.28", default-features = false, features = ["async-await"] }

embedded-hal = { version = "0.2.7" }
embedded-hal-async = { version = "1.0.0-rc.1", optional = true }
embedded-hal-bus = { version = "0.1.0-rc.1" }

usbd-hid = "0.6.1"
embedded-alloc = "0.5.0"
usb-device = { version = "0.2.9", features = ["defmt"] }

# nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice", features = ["defmt", "nrf52840", "s140", "ble-central", "ble-peripheral", "ble-l2cap", "ble-gatt-server", "ble-gatt-client", "ble-rssi", "ble-sec", "critical-section-impl", "usable-from-interrupts" ] }
nrf-softdevice = { path = "../nrf-softdevice/nrf-softdevice", features = ["defmt", "nrf52840", "s140", "ble-peripheral", "ble-gatt-server", "ble-rssi", "ble-sec", "critical-section-impl", "usable-from-interrupts" ] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

reactor = { version = "0.1.0", path = "reactor" }
reactor-macros = { version = "0.1.0", path = "reactor-macros" }
heapless = { version = "0.7.16", features = ["defmt", "defmt-impl"] }

[features]
default = [
	"nrf52840",
	"nightly",
]

# Hardware targets
rp = ["dep:embassy-rp"]
nrf = ["dep:embassy-nrf"]
stm32 = ["dep:embassy-stm32"]
nightly = [
	"static_cell/nightly",
	"embassy-usb",
	"embedded-hal-async",
	"embassy-executor/nightly",
	"embassy-nrf/nightly",
	"nrf-softdevice/nightly"
]

# nRF targets
nrf52840 = ["nrf"]
