name: Launchpad
features:
  - nrf52840
  - usb
  - softdevice

structs:
  - type: matrix::Matrix
    inputs:
      - pin: P0_04
        pull: Down
      - pin: P0_30
        pull: Down
      - pin: P1_14
        pull: Down
    outputs:
      - pin: P0_03
        level: Low
        drive: Standard
      - pin: P0_28
        level: Low
        drive: Standard
      - pin: P0_29
        level: Low
        drive: Standard
    direction: Row2Col
  - type: keymap_mid::Keymap
    keymap:
      - - [Intl1, Intl2, Intl3]
        - [Intl4, Intl5, Intl6]
        - [Intl7, Intl8, Intl9]
      - - [Kb1, Kb2, Kb3]
        - [Kb4, Kb5, Kb6]
        - [Kb7, Kb8, Kb9]
    hold_cycles: 1000
  - type: usb_hid::UsbHid
