[toolchain]
channel = "nightly-2023-08-19"
components = [ "rust-src", "rustfmt", "llvm-tools", "rust-analyzer" ]
targets = [
    "thumbv6m-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
    "riscv32imac-unknown-none-elf",
    "wasm32-unknown-unknown",
]
