[global]
# Device-specific configuration
name = "LaunchPad" # Name of the board
version = "1.0.0" # Revision of the board
serial = "123456" # Serial number of the device

# Conditional compilation
features = [
	"nrf52840", # Target MCU - assumes nrf
	"ble", # Enable BLE support
	"usb" # Enable USB support
]

# Publishers/Subscribers configuration
publishers = [ "matrix" ]
middleware = [ "keymap", "keyboard_report" ]
subscribers = [ "ble_hid", "usb_hid" ]
# nrf_softdevice = true

[matrix]
inputs = [
	{ pin = "P0_04", pull = "down" },
	{ pin = "P0_30", pull = "down" },
	{ pin = "P1_14", pull = "down" },
]
outputs = [
	{ pin = "P0_04", level = "low", drive = "standard" },
	{ pin = "P0_30", level = "low", drive = "standard" },
	{ pin = "P1_14", level = "low", drive = "standard" },
]
direction = "Row2Col"

[keymap]
# period = 2
layers = [
	[
		[ "Kb1", "Kb2", "Kb3", ],
		[ "Kb4", "Kb5", "Kb6", ],
		[ "Kb7", "Kb8", "Kb9" ],
	],
	[
		[ "Intl1", "Intl2", "Intl3", ],
		[ "Intl4", "Intl5", "Intl6", ],
		[ "Intl7", "Intl8", "Intl9" ],
	]
]

# [ble_hid]
