[package]
name = "reactor"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.6"
futures = { version = "0.3.30", default-features = false, features = ["async-await"] }
strum = { version = "0.26.2", default-features = false, features = ["derive"] }
